language: node_js
node_js:
  - "11.11"
sudo: required
services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
script:
  - docker exec -it emscripten emcc -O3 primes.c -o js/wasmprimes.js -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' -s ALLOW_MEMORY_GROWTH=1

before_deploy:
  - rm -rf .vscode/ experiments/ .gitignore .travis.yml *.md *.c
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: false
  github_token: $GITHUB_TOKEN
  on:
    branch: master
